import React, { useEffect } from 'react';
import { createPayment, verifyPayment } from '../../services/paymentService';
import { toast } from 'react-hot-toast';
import { db, auth } from '../../firebase';
import { setDoc, doc } from 'firebase/firestore';

interface RazorpayCheckoutProps {
  amount: number;
  currency: string;
  receipt: string;
  printJobs: string;
  shopId: string;
  generatedOrderId?: string;
  userProfile?: {
    name: string;
    mobile: string;
    email: string;
  };
  onSuccess: (response: any) => void;
  onError: (error: any) => void;
}

declare global {
  interface Window {
    Razorpay: any;
  }
}

const RazorpayCheckout: React.FC<RazorpayCheckoutProps> = ({
  amount,
  currency,
  receipt,
  printJobs,
  shopId,
  generatedOrderId,
  userProfile,
  onSuccess,
  onError,
}) => {
  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const generateOTP = (orderId: string) => {
    const otp = Math.floor(1000 + Math.random() * 9000).toString();
    return { otp };
  };

  useEffect(() => {
    const handlePayment = async () => {
      try {
        const res = await loadRazorpayScript();

        if (!res) {
          toast.error('Razorpay SDK failed to load. Are you online?');
          onError(new Error('Razorpay SDK failed to load'));
          return;
        }

        if (!window.Razorpay) {
          toast.error('Razorpay SDK loaded but window.Razorpay is unavailable');
          onError(new Error('window.Razorpay is undefined'));
          return;
        }

        // 1. Create Order via Backend
        const orderData = await createPayment({
          amount,
          currency,
          receipt,
          notes: {
            printJobs,
            shopId,
          },
        });

        if (!orderData) {
          throw new Error('Failed to create order');
        }

        const options: any = {
          key: orderData.key_id, // Access key_id from backend response
          amount: orderData.amount,
          currency: orderData.currency,
          name: "QuickXerox",
          description: "Print Job Payment",
          image: "/icon-192x192.png", // Ensure this exists or use a remote URL
          handler: async function (response: any) {
            try {
              toast.loading('Verifying payment...');
              const isVerified = await verifyPayment(
                response.razorpay_payment_id,
                response.razorpay_order_id,
                response.razorpay_signature
              );

              if (isVerified) {
                // Save Order to Firestore
                try {
                  const items = JSON.parse(printJobs);
                  // Use Razorpay Order ID if present, otherwise use the one generated by Cart
                  const orderId = response.razorpay_order_id || generatedOrderId || `ORD-${Date.now()}`;

                  // Priority: Prop (Directly from useProfile) -> Auth -> Session -> Local -> Fallback
                  const authUser = auth.currentUser;
                  const userName = userProfile?.name || authUser?.displayName || sessionStorage.getItem('userName') || localStorage.getItem('userName') || 'Guest';
                  const userPhone = userProfile?.mobile || authUser?.phoneNumber || sessionStorage.getItem('userPhone') || localStorage.getItem('userPhone') || '';
                  const userEmail = userProfile?.email || authUser?.email || sessionStorage.getItem('userEmail') || localStorage.getItem('userEmail') || '';

                  const newOrder = {
                    id: orderId,
                    customerName: userName,
                    customerPhone: userPhone,
                    customerEmail: userEmail,
                    sellerPhone: '',
                    items: items,
                    total: amount,
                    status: 'pending',
                    timestamp: new Date().toISOString(),
                    shopId: shopId,
                    isPaid: true,
                    paymentId: response.razorpay_payment_id,
                    otpVerified: false,
                    otpGeneratedAt: new Date().toISOString(),
                    otp: generateOTP(orderId).otp // Persist OTP to database for seller visibility
                  };

                  // Use setDoc to force the Document ID to match our Order ID
                  await setDoc(doc(db, 'orders', orderId), newOrder);
                  console.log('Order saved to Firestore:', newOrder);

                  toast.dismiss();
                  toast.success('Order placed successfully!');

                  // Pass the generated Order ID and OTP back
                  onSuccess({ ...response, orderId: orderId, otp: newOrder.otp });
                } catch (dbError: any) {
                  console.error('Error saving order to DB:', dbError);
                  toast.dismiss();
                  toast.error(`Critical Error: Order not saved. ${dbError.message}`);
                  // DO NOT call onSuccess here, so the user knows it failed
                  onError(dbError);
                }
              } else {
                toast.dismiss();
                toast.error('Payment verification failed');
                onError('Payment verification failed');
              }
            } catch (error) {
              toast.dismiss();
              console.error("Verification Error", error);
              toast.error('Payment verification error');
              onError(error);
            }
          },
          prefill: {
            name: localStorage.getItem('userName') || 'Customer',
            email: localStorage.getItem('userEmail') || 'customer@example.com',
            contact: localStorage.getItem('userPhone') || '',
          },
          notes: {
            printJobs,
            shopId,
          },
          theme: {
            color: "#3b82f6",
          },
          modal: {
            ondismiss: function () {
              onError('Payment cancelled by user');
            }
          }
        };

        // Add order_id only if it exists (Server-side flow)
        if (orderData.orderId) {
          options.order_id = orderData.orderId;
        }

        const rzp1 = new window.Razorpay(options);
        rzp1.on('payment.failed', function (response: any) {
          console.error(response.error);
          onError(response.error);
          toast.error(response.error.description || 'Payment failed');
        });

        rzp1.open();

      } catch (error) {
        console.error('Payment initiation error:', error);
        onError(error);
        toast.error('Failed to initiate payment');
      }
    };

    handlePayment();
  }, [amount, currency, receipt, printJobs, shopId, generatedOrderId, userProfile]);

  return null;
};

export default RazorpayCheckout;